name: Nasza nazwa

on: push

jobs:
 tests:
    runs-on: ubuntu-latest
    steps:
    # Checkout kodu z repozytorium
    - name: Checkout
      uses: actions/checkout@v4 
    # Ustawiamy wersję Node.js
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    # Instalujemy zależności
    - name: Install dependencies
      run: npm install
    # Wykonujemy testy  
    - name: Run tests
      run: npm test
